### ISSUE TITLE
Two lines title

### ISSUE THREAD

**Issue by amelgrenier** [brandawg/Cranfield_Thesis_Template#3]
\title{title of the document

in two lines}

This command-line does not work with the \maketitlepages command. Every option to have the title in two lines (\\, \linebreak, and the example above) was not accepted. Could this functionality be added?

Thank you

**Comment by brandawg** [comment]
Just to confirm, you want to force an additional line break within the title of the document? Because LaTeX should just line break the title automatically if your title is long enough?

**Comment by brandawg** [comment]
Just to confirm, you want to force an additional line break within the title of the document? Because LaTeX should just line break the title automatically if your title is long enough.

However, if this is the case you can just use `\protect\\` within the title command. 

Where `\\` is the line break and `\protect` is just a command to force it to happen within the title command of the thesis template class.

I haven't tested this substantially so please let me know if it causes you any additional issues, but it should be fine though :)

Example usage:
```
\title{Example Thesis Title With \protect\\ A Forced Line Break}
```
![image](https://user-images.githubusercontent.com/14260752/72707100-8ce17200-3b57-11ea-8d1c-305bd69fa20f.png)

**Comment by amelgrenier** [comment]
Thank you very much!
It seems to work without problems and that is exactly what I needed. I will let you know if somehow it causes other issues though.
